name: simpletodo

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_web
    ports: 
      - "3000:4173"
    depends_on:
      - server
    networks:
      - frontend

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_server
    ports:
      - 8000:8080
    environment:
      - DB_HOST=db
      - DB_NAME=tododb
      - DB_SA_PASSWORD=Password123
    depends_on: 
      - db
    networks:
      - frontend
      - backend

  db:
    container_name: tododb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 8002:1433
    environment:
      MSSQL_SA_PASSWORD: Password123
      ACCEPT_EULA: Y
    networks:
     - backend
    volumes:
     - db_data:/var/opt/mssql

volumes:
  db_data:

networks:
  backend:
  frontend:
